# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "COINiD.xcodeproj")
    build_app(scheme: "COINiD")
    upload_to_testflight(skip_waiting_for_build_processing: true)
    slack(
    	message: "Ny Vault på väg till TestFlight!",
    	default_payloads: [],
    	slack_url: 'https://hooks.slack.com/services/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'
    )
  end
end
