# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "COINiD.xcodeproj")
    build_app(scheme: "COINiD")
    upload_to_testflight(skip_waiting_for_build_processing: true)

    slack(
      message: "New Vault coming to Testflight!",
      default_payloads: [],
      slack_url: ENV['SLACK_URL']
    )
  end
end
