default_platform(:android)

platform :android do

  lane :beta do |options|
    if !options[:time]
      puts("Missing options...")
      next
    end

    bump_version_code

    rootDir = "..";
    shRootDir = "../.."; #sh cwd is android/fastlane
    buildDir = "builds/vault";

    FileUtils.mkdir_p("#{shRootDir}/#{buildDir}/latest") unless File.directory?("#{shRootDir}/#{buildDir}/latest")
    FileUtils.mkdir_p("#{shRootDir}/#{buildDir}/#{options[:time]}") unless File.directory?("#{shRootDir}/#{buildDir}/#{options[:time]}")

    gradle(task: "clean assembleRelease")

    FileUtils.mv("#{shRootDir}/android/app/build/outputs/apk/release/app-release.apk", "#{shRootDir}/#{buildDir}/latest/latest-coinid-vault.apk")
    FileUtils.cp("#{shRootDir}/#{buildDir}/latest/latest-coinid-vault.apk", "#{shRootDir}/#{buildDir}/#{options[:time]}/#{options[:time]}-coinid-vault.apk")

    upload_to_play_store(
      package_name: (options[:package_name]).to_s,
      apk: "#{rootDir}/#{buildDir}/latest/latest-coinid-vault.apk",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      track: "beta",
    )

    message_slack(options)
  end


  lane :message_slack do |options|
    slack(
      message: "New #{options[:coin]} Vault coming to Play Store!",
      default_payloads: [],
      slack_url: ENV['SLACK_URL']
    )
  end

  lane :bump_version_code do
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/

    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s

    f = File.new(path, 'w')
    f.write(s)
    f.close
  end
end
